### ISSUE TITLE
video with Images 

### ISSUE THREAD

**Issue by denno640** [nihk/videopager#6]
first of all:Great code! I would like to display images and video in the same viewpager with a VideosViewHolder and an ImagesViewHolder. Please advise on how to go about this.

**Comment by nihk** [comment]
thanks for reaching out, @denno640. the app in this repo wasn't built with that use-case in mind, unfortunately. i think if you wanted to include other arbitrary items in a list/pager like the one this repo has, then there would need to be a significant amount of change. likely the best approach for that is to have 1 exoplayer and 1 playerview instance per VideoViewHolder.

**Comment by denno640** [comment]
Hi @nihk Thank you for your response. I think I will use your advise and try to make the changes. I will be guided by your approach. Thanks alot!
